version: '3'

services:
    mongo-express:
        image: mongo-express
        ports:
          - 8081:8081
        environment:
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_BASICAUTH_USERNAME: ${DB_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
            ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
        links:
            - mongo
        networks:
            - mongo-compose-network

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "27017:27017"
        volumes:
            - ./volumes:/data/db
        networks:
            - mongo-compose-network

networks:
    mongo-compose-network:
        driver: bridge
